### ISSUE TITLE
RocketMod <-> OpenMod Economy bridge

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#319]
Implementation for:
```yaml
rocketmodIntegration:
  # Set the economy system to use
  # Available values:
  # - RocketMod_Uconomy: OpenMod will use Uconomy for its economy system (default)
  # - OpenMod_Uconomy:   The installed OpenMod economy plugin will replace Uconomy
  # - Separate:          OpenMod and RocketMod will not have synced economy
  economySystem: RocketMod_Uconomy
```
