### ISSUE TITLE
autoexec.yaml file

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#334]
Automatically execute commands once, on startup or periodically (crontab syntax).
Needed for #275 so it can auto-run economy migration commands after a restart.

```yaml
commands:
  - command: openmod upgrade
    execute: 0 0 * * 0 # Every Sunday at 0:00 (crontab syntax)
    enabled: true 
  - command: openmod restart
    execute: 0 3 * * * # Restart everyday at 3 AM
    enabled: false 
  - command: openmod purge
    execute: startup # Purge all packages on every startup
    enabled: false
  - command: economy migrate
    execute: once # Will auto remove this command from the file once it's executed
    enabled: true
````
