### ISSUE TITLE
Add openmod.commands.yaml

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#52]
Configure command names, aliases,  etc. (planned after release)

Format:
```yaml
- id: OpenMod.Commands.OpenModCommands.CommandOpenMod
  name: openmod
  aliases: [ "om" ]
  priority: Highest # can be one of "Highest, High, Normal, Low, Lowest"
  data: { } # can be used by plugins
  enabled: true
- id: OpenMod.Commands.OpenModCommands.CommandOpenModInstall
  parentId: OpenMod.Commands.OpenModCommands.CommandOpenMod
  name: openmod
  aliases: [ "i", "+" ]
  priority: Highest
  data: { }
  enabled: true
```
