### ISSUE TITLE
Wrong subcommands description in help.md file

### ISSUE THREAD

**Issue by Pandetthe** [openmod/openmod#684]
Subcommands' command is ignored in commands list in help.md file but only when there are two the same commands but for different actors
Example
```
## Commands
- voicerange <list/get/switch>: Manage your voice range.
  id: Alpalis.VoiceSystem.Commands.VoiceRangeCommand+Root
- voicerange <player>: Get someone's voice range. == should be voicerange get
  id: Alpalis.VoiceSystem.Commands.VoiceRangeCommand+GetConsole
- voicerange [player]: Get yours or someone's voice range. == should be voicerange get
  id: Alpalis.VoiceSystem.Commands.VoiceRangeCommand+GetUnturned
  permissions:
  - Alpalis.VoiceSystem:commands.voicerange.get.other: Allows to get voice range of other player.
- voicerange <whisper/talk/shout> <player>: Change voice range. == should be voicerange switch
  id: Alpalis.VoiceSystem.Commands.VoiceRangeCommand+SwitchConsole
- voicerange [whisper/talk/shout] [player]: Change voice range. == should be voicerange switch
  id: Alpalis.VoiceSystem.Commands.VoiceRangeCommand+SwitchUnturned
  permissions:
  - Alpalis.VoiceSystem:commands.voicerange.switch.other: Allows to change voice range of other player.
- voicerange list: Get list of voice ranges. == but here is working fine
  id: Alpalis.VoiceSystem.Commands.VoiceRangeCommand+List
```
