### ISSUE TITLE
`packages.yaml` ignore package id in specific package

### ISSUE THREAD

**Issue by sunnamed434** [openmod/openmod#794]
```yaml
packages:
  - id: Package
    version: latest
    ignores: PackageName # new line
```
